name: Data Collection Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Files to Azure Storage
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Upload Scripts
    - name: Upload Scripts to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --destination "scripts" \
          --source "scripts"

    # Upload Data
    - name: Upload Data to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --destination "data" \
          --source "data"

    # Upload API Code
    - name: Upload API Code to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
          --destination "api" \
          --source "api"